# talib/talib.pyi
import numpy as np   
from typing import Union, Optional

# 使用 Union 支持 numpy array 或 list 输入
ArrayLike = Union[np.ndarray, list]

def SMA(real: ArrayLike, timeperiod: int = 30) -> np.ndarray: ...
def RSI(real: ArrayLike, timeperiod: int = 14) -> np.ndarray: ...
def MACD(real: ArrayLike, fastperiod: int = 12, slowperiod: int = 26, signalperiod: int = 9) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def BBANDS(real: ArrayLike, timeperiod: int = 5, nbdevup: float = 2, nbdevdn: float = 2, matype: int = 0) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...